SELECT
    YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
    ABS(B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV,
    A.ID
FROM ECOLI_DATA A
LEFT JOIN
    (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA A
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) B
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC